services:

  backend:
    build: ./backend

    ports:
      - "8000:8000"

    volumes:
      - ./RAG:/app/RAG
      - ./ml_models:/app/ml_models

  frontend:
    build: ./frontend

    ports:
      - "8501:8501"

    depends_on:
      - backend